### ISSUE TITLE
rename my_zome something more relevant

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn-hc#42]
Note that if the name of the zome is changed, the [acorn-ui project](/h-be/acorn-ui) should be updated to change any references to "my_zome" to whatever it is changed to

**Comment by hector0513** [comment]
ready, change the name to "holo_acorn"

**Comment by Connoropolous** [comment]
cool. I notice the `.cargo` folder got committed and is HUGE, so maybe we can remove it again, and it to the `.gitignore` file?

**Comment by Connoropolous** [comment]
and a github tip for you: 

when you create a git commit that addresses a certain github issue, in the commit message, you can say "closes #42" and it will automatically close this issue when you push that commit to github.

**Comment by Connoropolous** [comment]
closed by https://github.com/h-be/acorn-hc/commit/50f0109e36d122ee2a15e3ab1047147a67d6d110
