### ISSUE TITLE
TimeOut error in the test 

### ISSUE THREAD

**Issue by hector0513** [h-be/acorn-hc#45]
I am doing a test to the "fetch_goals" function, and I'm getting a timeout error.

**Comment by hector0513** [comment]
https://github.com/h-be/acorn-hc/tree/Fail_test

**Comment by Connoropolous** [comment]
Hi @hector0513 I will check this out now. 

Let's see...

**Comment by Connoropolous** [comment]
@hector0513 

I've determined that using the so-called 'memory' version of networking might not work as well for us as one of the other options, such as 'sim2h'. I can explain more if you want. 

But here's how to use it:
Open up 2 nix-shells
In one, run `hc-sim2h-server`

In another, run the tests.
`hc test`

This depends on this new network configuration that I've provided:
https://github.com/h-be/acorn-hc/commit/3bd752ef6be1a4fdd33f1b1f381817376563b040#diff-910eb6f57886ca16c136101fb1699231R34

**Comment by Connoropolous** [comment]
`hc test` is working for me now, with this configuration

**Comment by hector0513** [comment]
i can't run hc-sim2h-server

**Comment by Connoropolous** [comment]
Ah, strange!

Ok, as suggested by Jhonatan maybe move on from trying out testing and focus elsewhere
