### ISSUE TITLE
removing an agent from a Goal causes the app to stop responding

### ISSUE THREAD

**Issue by Connoropolous** [h-be/acorn-hc#69]

**Comment by acatinon** [comment]
I don't understand how to reproduce this bug

**Comment by Connoropolous** [comment]
Ah, I am thinking we've overcome this. We kind of breezed through some bugs without looking at everything that was in the issue tracking, so this one might have gotten fixed.

Looking for other spots to contribute? Happy to chat and make some recommendations or connect
